name: Deploy to GitHub page

on:
  push:
    #branches:
    #  - main
    tags:
      - '*.*.*'

jobs:
  build-prod-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build-prod-job"
  auto-deploy-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "auto-deploy-job"
