name: Deploy to GitHub page

on:
  push:
    #branches:
    #  - main
    tags:
      - '*.*.*'

jobs:
  build-prod-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5

      - name: Set Nodejs version to 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build production (create dist folder)
        run: npm run build

      - name: Upload dist folder artifact
        uses: actions/upload-artifact@v5
        with:
          name: dist-production
          path: dist

  auto-deploy-job:
    runs-on: self-hosted
    needs: build-prod-job
    steps:
      - name: Download dist folder artifact
        uses: actions/download-artifact@v6
        with:
          name: dist-production
          path: dist

      - run: ls dist
      
      - uses: actions/checkout@v5

      - name: Deploy to GitHub page
        uses: Serhiika/VuePagesAction@1.0.4
        with:
          username: ${{ github.actor }}
          reponame: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
